### ISSUE TITLE
机器人在长时间挂机后 会报错  然后导致服务器卡死

### ISSUE THREAD

**Issue by screamingshark** [appe233/TS3AudioBot_docker#5]
16:00:27.2867| WARN|0| Previous resend tick didn't finish
16:01:02.1513| WARN|0| Previous resend tick didn't finish
16:01:05.1515| WARN|0| Previous resend tick didn't finish
16:01:28.1453| WARN|0| Previous resend tick didn't finish
16:01:33.2272| WARN|0| Previous resend tick didn't finish
16:01:41.2266| WARN|0| Previous resend tick didn't finish
16:01:58.1580| WARN|0| Previous resend tick didn't finish
16:01:45.1719| WARN|0| Raw LONG: 941ms
16:02:03.1686| WARN|0| Previous resend tick didn't finish
16:02:15.1562| WARN|0| Previous resend tick didn't finish
16:02:15.1688| WARN|0| Previous resend tick didn't finish
16:02:14.1978| WARN|0| Previous resend tick didn't finish
16:02:16.1545| WARN|0| Previous resend tick didn't finish
16:02:16.1637| WARN|0| Previous resend tick didn't finish
16:02:17.1775| WARN|0| Previous resend tick didn't finish
16:02:17.1634| WARN|0| Previous resend tick didn't finish
16:02:18.2141| WARN|0| Previous resend tick didn't finish
16:02:18.2077| WARN|0| Previous resend tick didn't finish
16:02:19.2158| WARN|0| Previous resend tick didn't finish
16:02:19.2185| WARN|0| Previous resend tick didn't finish
16:02:20.1712| WARN|0| Previous resend tick didn't finish
16:02:21.1516| WARN|0| Previous resend tick didn't finish
16:02:21.1551| WARN|0| Previous resend tick didn't finish
16:02:20.2483| WARN|0| Previous resend tick didn't finish
16:02:22.1451| WARN|0| Previous resend tick didn't finish
16:02:21.2518| WARN|0| Previous resend tick didn't finish
16:02:22.1471| WARN|0| Previous resend tick didn't finish
16:02:23.1569| WARN|0| Previous resend tick didn't finish
16:02:24.1749| WARN|0| Previous resend tick didn't finish
16:02:24.1466| WARN|0| Previous resend tick didn't finish
16:02:23.1485| WARN|0| Previous resend tick didn't finish
16:02:25.1624| WARN|0| Previous resend tick didn't finish
16:02:25.1768| WARN|0| Previous resend tick didn't finish
16:02:25.2350| WARN|0| Previous resend tick didn't finish
16:02:26.1732| WARN|0| Previous resend tick didn't finish
16:02:26.1732| WARN|0| Previous resend tick didn't finish
16:02:27.1834| WARN|0| Previous resend tick didn't finish
16:02:28.1550| WARN|0| Previous resend tick didn't finish
16:02:28.1550| WARN|0| Previous resend tick didn't finish
16:02:27.1834| WARN|0| Previous resend tick didn't finish
16:02:29.1667| WARN|0| Previous resend tick didn't finish
16:02:29.1667| WARN|0| Previous resend tick didn't finish
16:02:30.1507| WARN|0| Previous resend tick didn't finish
16:02:30.1492| WARN|0| Previous resend tick didn't finish
16:02:31.1527| WARN|0| Previous resend tick didn't finish
16:02:31.1502| WARN|0| Previous resend tick didn't finish
16:02:31.1463| WARN|0| Previous resend tick didn't finish
16:02:32.1582| WARN|0| Previous resend tick didn't finish
16:02:32.1541| WARN|0| Previous resend tick didn't finish
16:02:33.1587| WARN|0| Previous resend tick didn't finish
16:02:33.1749| WARN|0| Previous resend tick didn't finish
16:02:58.5042| INFO|0| Trying to reconnect because of Timeout. Delaying reconnect for 1 seconds

**Comment by appe233** [comment]
啊，我这里也有这个问题。我认为应该是原插件的问题。目前看来是内存问题。我尝试限制过容器的内存，然后崩的更早了。

**Comment by screamingshark** [comment]
> 啊，我这里也有这个问题。我认为应该是原插件的问题。目前看来是内存问题。我尝试限制过容器的内存，然后崩的更早了。

我也发现了 触发内存上限了  难崩

**Comment by appe233** [comment]
你的内存是多大？我在我的 1 G 服务器上大概几个小时就崩。

**Comment by appe233** [comment]
你试一下加上：
`COMPlus_gcServer=0`
这个环境变量到容器里。

```yaml
services:
  musicapi:
    image: binaryify/netease_cloud_music_api:latest
    container_name: netease-cloud-music-api
    networks:
      - ts3audiobot-netease

  ts3audiobot:
    image: appe233/ts3audiobot:0.12.0
    container_name: ts3audiobot
    volumes:
      - type: bind
        source: ./bot.toml
        target: /app/bots/default/bot.toml
    networks:
      - ts3audiobot-netease
    environment:
      - COMPlus_gcServer=0

networks:
  ts3audiobot-netease:
    name: ts3audiobot-netease
```
